### ISSUE TITLE
UI Apps

### ISSUE THREAD

**Issue by TommyQC** [jojos38/Improved-Siren-Mod#1]
The UI apps doesn't show when I add them

**Comment by jojos38** [comment]
Hey, did you try the Github version or the repository version? The Github version should be fixed.
The repository one is waiting for approval

**Comment by TommyQC** [comment]
> Hey, did you try the Github version or the repository version? The Github version should be fixed. The repository one is waiting for approval

I only tried the repository version, I'll try the GitHub one
