### ISSUE TITLE
AI seem broken

### ISSUE THREAD

**Issue by TinnyTerr** [jojos38/Improved-Siren-Mod#3]
AI are broken when using the traffic lights and either the mod is incompatible with a mod or a recent AI update.

Behaviour:
Ai seem stuck at traffic lights like the light is red all the time

It is definitely a conflict including your mod as it is the only one it happens on if it enabled.
If you do handle AI in any way on traffic lights, could you at least point me in the right direction and I'll see if I can figure it out, learning LUA in the process.

**Comment by jojos38** [comment]
Hey, I'm sorry I stopped modding for the game but the fucntions that cause the issue are very likely the injects at line 150 of https://github.com/jojos38/Improved-Siren-Mod/blob/main/lua/vehicle/extensions/auto/sirenmodVE.lua

These functions replace the original game function and they probably changed in the game so they cause issues.
You might want to simply find back these functions in the game and update them in the mod code

**Comment by TinnyTerr** [comment]
No probs. I'll look and try my luck but probably wont amount to much. Thanks though!
